const std = @import("std");

pub const keyboard_key_count = 256;
// Can be stored in AVX register (YMMx)
pub const KeyboardState = std.bit_set.IntegerBitSet(keyboard_key_count);

pub const Mod = enum {
    shift,
    ctrl,
    alt,
    super,
    caps,
    num,
};

pub const ModState = packed struct {
    shift: bool = false,
    ctrl: bool = false,
    alt: bool = false,
    super: bool = false,
    caps: bool = false,
    num: bool = false,
};

pub const KeyEventType = enum {
    press,
    release,
    repeat,
};

pub const KeyEvent = struct {
    type: KeyEventType,
    mods: ModState = .{},
    /// Raw platform scancode (hardware key position, platform-specific).
    code: u32,
    /// Platform-neutral virtual key symbol. Use the `Key` enum for comparisons.
    key: Key = .unknown,
};

/// Platform-neutral virtual key enum.
/// All platforms map their native key codes into this enum so that
/// App.zig can handle input without any platform-specific magic numbers.
pub const Key = enum(u32) {
    unknown = 0,

    // --- Printable / character keys (match ASCII/Unicode codepoints) ---
    space = ' ',
    apostrophe = '\'',
    comma = ',',
    minus = '-',
    period = '.',
    slash = '/',

    @"0" = '0',
    @"1" = '1',
    @"2" = '2',
    @"3" = '3',
    @"4" = '4',
    @"5" = '5',
    @"6" = '6',
    @"7" = '7',
    @"8" = '8',
    @"9" = '9',

    semicolon = ';',
    equal = '=',

    a = 'a',
    b = 'b',
    c = 'c',
    d = 'd',
    e = 'e',
    f = 'f',
    g = 'g',
    h = 'h',
    i = 'i',
    j = 'j',
    k = 'k',
    l = 'l',
    m = 'm',
    n = 'n',
    o = 'o',
    p = 'p',
    q = 'q',
    r = 'r',
    s = 's',
    t = 't',
    u = 'u',
    v = 'v',
    w = 'w',
    x = 'x',
    y = 'y',
    z = 'z',

    left_bracket = '[',
    backslash = '\\',
    right_bracket = ']',
    grave = '`',

    // --- Control keys (values above Unicode range to avoid clashing) ---
    enter = 0x110000,
    escape,
    backspace,
    tab,
    delete,
    insert,

    // --- Arrow keys ---
    arrow_up,
    arrow_down,
    arrow_left,
    arrow_right,

    // --- Navigation ---
    home,
    end,
    page_up,
    page_down,

    // --- Function keys ---
    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,

    // --- Modifier keys ---
    left_shift,
    right_shift,
    left_ctrl,
    right_ctrl,
    left_alt,
    right_alt,
    left_super,
    right_super,
    caps_lock,
    num_lock,
    scroll_lock,

    // --- Numpad ---
    kp_0,
    kp_1,
    kp_2,
    kp_3,
    kp_4,
    kp_5,
    kp_6,
    kp_7,
    kp_8,
    kp_9,
    kp_decimal,
    kp_divide,
    kp_multiply,
    kp_subtract,
    kp_add,
    kp_enter,
    kp_equal,

    _,
};

/// Map an XKB / X11 keysym to a platform-neutral `Key`.
/// XKB keysyms for printable ASCII characters equal their Unicode codepoints.
pub fn keyFromXkbKeysym(sym: u32) Key {
    // Printable letters — normalise to lowercase
    if (sym >= 'a' and sym <= 'z') return @enumFromInt(sym);
    if (sym >= 'A' and sym <= 'Z') return @enumFromInt(sym + 32);
    if (sym >= '0' and sym <= '9') return @enumFromInt(sym);
    switch (sym) {
        ' '  => return .space,
        '\'' => return .apostrophe,
        ','  => return .comma,
        '-'  => return .minus,
        '.'  => return .period,
        '/'  => return .slash,
        ';'  => return .semicolon,
        '='  => return .equal,
        '['  => return .left_bracket,
        '\\' => return .backslash,
        ']'  => return .right_bracket,
        '`'  => return .grave,
        else => {},
    }
    return switch (sym) {
        0xFF0D, 0xFF8D => .enter,
        0xFF1B         => .escape,
        0xFF08         => .backspace,
        0xFF09         => .tab,
        0xFFFF         => .delete,
        0xFF63         => .insert,
        0xFF52         => .arrow_up,
        0xFF54         => .arrow_down,
        0xFF51         => .arrow_left,
        0xFF53         => .arrow_right,
        0xFF50         => .home,
        0xFF57         => .end,
        0xFF55         => .page_up,
        0xFF56         => .page_down,
        0xFFBE         => .f1,
        0xFFBF         => .f2,
        0xFFC0         => .f3,
        0xFFC1         => .f4,
        0xFFC2         => .f5,
        0xFFC3         => .f6,
        0xFFC4         => .f7,
        0xFFC5         => .f8,
        0xFFC6         => .f9,
        0xFFC7         => .f10,
        0xFFC8         => .f11,
        0xFFC9         => .f12,
        0xFFE1, 0xFFE2 => .left_shift,
        0xFFE3         => .left_ctrl,
        0xFFE4         => .right_ctrl,
        0xFFE9         => .left_alt,
        0xFFEA         => .right_alt,
        0xFFEB         => .left_super,
        0xFFEC         => .right_super,
        0xFFE5         => .caps_lock,
        0xFF7F         => .num_lock,
        0xFF14         => .scroll_lock,
        0xFFB0         => .kp_0,
        0xFFB1         => .kp_1,
        0xFFB2         => .kp_2,
        0xFFB3         => .kp_3,
        0xFFB4         => .kp_4,
        0xFFB5         => .kp_5,
        0xFFB6         => .kp_6,
        0xFFB7         => .kp_7,
        0xFFB8         => .kp_8,
        0xFFB9         => .kp_9,
        0xFFAE         => .kp_decimal,
        0xFFAF         => .kp_divide,
        0xFFAA         => .kp_multiply,
        0xFFAD         => .kp_subtract,
        0xFFAB         => .kp_add,
        0xFFBD         => .kp_equal,
        else           => .unknown,
    };
}

/// Map a GLFW key constant to a platform-neutral `Key`.
/// GLFW key values: https://www.glfw.org/docs/latest/group__keys.html
pub fn keyFromGlfw(glfw_key: i32) Key {
    return switch (glfw_key) {
        'A'...'Z' => @enumFromInt(glfw_key + 32), // normalise to lowercase
        '0'...'9' => @enumFromInt(glfw_key),
        ' '  => .space,
        '\'' => .apostrophe,
        ','  => .comma,
        '-'  => .minus,
        '.'  => .period,
        '/'  => .slash,
        ';'  => .semicolon,
        '='  => .equal,
        '['  => .left_bracket,
        '\\' => .backslash,
        ']'  => .right_bracket,
        '`'  => .grave,
        256  => .escape,
        257  => .enter,
        258  => .tab,
        259  => .backspace,
        260  => .insert,
        261  => .delete,
        262  => .arrow_right,
        263  => .arrow_left,
        264  => .arrow_down,
        265  => .arrow_up,
        266  => .page_up,
        267  => .page_down,
        268  => .home,
        269  => .end,
        280  => .caps_lock,
        281  => .scroll_lock,
        282  => .num_lock,
        290  => .f1,
        291  => .f2,
        292  => .f3,
        293  => .f4,
        294  => .f5,
        295  => .f6,
        296  => .f7,
        297  => .f8,
        298  => .f9,
        299  => .f10,
        300  => .f11,
        301  => .f12,
        320  => .kp_0,
        321  => .kp_1,
        322  => .kp_2,
        323  => .kp_3,
        324  => .kp_4,
        325  => .kp_5,
        326  => .kp_6,
        327  => .kp_7,
        328  => .kp_8,
        329  => .kp_9,
        330  => .kp_decimal,
        331  => .kp_divide,
        332  => .kp_multiply,
        333  => .kp_subtract,
        334  => .kp_add,
        335  => .kp_enter,
        336  => .kp_equal,
        340  => .left_shift,
        341  => .left_ctrl,
        342  => .left_alt,
        343  => .left_super,
        344  => .right_shift,
        345  => .right_ctrl,
        346  => .right_alt,
        347  => .right_super,
        else => .unknown,
    };
}

/// Map a Win32 virtual key code (VK_*) to a platform-neutral `Key`.
pub fn keyFromWin32(vk: u32) Key {
    return switch (vk) {
        0x41...0x5A => @enumFromInt(vk + 32), // VK_A..VK_Z -> lowercase
        0x30...0x39 => @enumFromInt(vk),       // VK_0..VK_9
        0xBC => .comma,
        0xBE => .period,
        0xBF => .slash,
        0xBA => .semicolon,
        0xBB => .equal,
        0xBD => .minus,
        0xDB => .left_bracket,
        0xDC => .backslash,
        0xDD => .right_bracket,
        0xDE => .apostrophe,
        0xC0 => .grave,
        0x0D => .enter,
        0x1B => .escape,
        0x08 => .backspace,
        0x09 => .tab,
        0x2E => .delete,
        0x2D => .insert,
        0x26 => .arrow_up,
        0x28 => .arrow_down,
        0x25 => .arrow_left,
        0x27 => .arrow_right,
        0x24 => .home,
        0x23 => .end,
        0x21 => .page_up,
        0x22 => .page_down,
        0x20 => .space,
        0x70 => .f1,
        0x71 => .f2,
        0x72 => .f3,
        0x73 => .f4,
        0x74 => .f5,
        0x75 => .f6,
        0x76 => .f7,
        0x77 => .f8,
        0x78 => .f9,
        0x79 => .f10,
        0x7A => .f11,
        0x7B => .f12,
        0xA0 => .left_shift,
        0xA1 => .right_shift,
        0xA2 => .left_ctrl,
        0xA3 => .right_ctrl,
        0xA4 => .left_alt,
        0xA5 => .right_alt,
        0x5B => .left_super,
        0x5C => .right_super,
        0x14 => .caps_lock,
        0x90 => .num_lock,
        0x91 => .scroll_lock,
        0x60 => .kp_0,
        0x61 => .kp_1,
        0x62 => .kp_2,
        0x63 => .kp_3,
        0x64 => .kp_4,
        0x65 => .kp_5,
        0x66 => .kp_6,
        0x67 => .kp_7,
        0x68 => .kp_8,
        0x69 => .kp_9,
        0x6E => .kp_decimal,
        0x6F => .kp_divide,
        0x6A => .kp_multiply,
        0x6D => .kp_subtract,
        0x6B => .kp_add,
        else => .unknown,
    };
}

pub const Xkb = @import("Xkb.zig");
