when:
  - event: push
    branch: master

steps:
  - name: build
    image: alpine

    commands:
      - |
        apk update && apk add --no-cache \
          curl \
          bash \
          xz \
          git \
          ca-certificates \
          bison \
          glslang

      - curl -sSf https://raw.githubusercontent.com/MingFei2001/install-zig/refs/heads/main/install-zig.sh | bash

      - zig build
