when:
  - event: push
    branch: master

steps:
  - name: build
    image: ziglings/ziglang

    commands:
      - apk update && apk add --no-cache \
          sudo \
          curl \
          bash \
          xz \
          git \
          ca-certificates \
          bison \
          glslang

      - zig build
