when:
  - event: push
    branch: master

steps:
  - name: check build and run tests
    image: alpine

    commands:
      - |
        apk update && apk add --no-cache \
          sudo \
          curl \
          bash \
          xz \
          git \
          ca-certificates \
          bison \
          glslang

      - curl -sSf https://raw.githubusercontent.com/MingFei2001/install-zig/refs/heads/main/install-zig.sh | bash

      - TEMP_BIN_DIR=$(mktemp -d)

      - curl -sSfL https://zigcli.liujiacai.net/install.sh | sh -s -- --install-dir "$TEMP_BIN_DIR"

      - export PATH="$TEMP_BIN_DIR:$PATH"

      - zigfetch .

      - zig build

      - zig build test
