name: release_build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target_os: native # building for linux needs to be native
            target_arch: x64_64
            render_backend: OpenGL

          - target_os: windows
            target_arch: x64_64
            render_backend: OpenGL


    runs-on: ubuntu-latest

    steps:
      - name: Install zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build release binaries
        run: zig build --release=fast \
              -Dtarget=${{ matrix.target_arch }}-${{ matrix.target_os }} \
              -Drender-backend=${{ matrix.render_backend }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zerotty
          path: zig-out/bin/*
  
  release:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

