name: unit_test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxkbcommon-dev \
            mesa-vulkan-drivers \
            spirv-tools \
            glslang-dev

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Build and Run tests
        run: zig build test

      - name: Cache zig build
        uses: actions/cache@v4
        with:
          path: .zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'build.zig.zon', 'build/**/*.zig') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'build.zig.zon', 'build/**/*.zig') }}-
            ${{ runner.os }}-zig-


