name: unit_test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install zig
        uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.15.1

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache zig build output
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/zig
            zig-cache
            .zig-cache
          key: zig-${{ matrix.zig }}-${{ matrix.arch }}-${{ runner.os }}-${{ hashFiles('build.zig', 'build.zig.zon', 'build/**/*.zig') }}
          restore-keys: |
            zig-${{ matrix.zig }}-${{ matrix.arch }}-${{ runner.os }}-

      - name: Build and Run tests
        run: zig build test
