name: unit_test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux-gnu

          - os: windows-latest
            target: x86_64-windows-gnu

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install zig
        uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.15.1

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Build and Run tests
        run: |
          zig build test \
            -Dtarget=${{ matrix.target }} \
            -Dno-lsp-check \

      - name: Make test badge
        uses: action-badges/core@0.3.1
        with:
          label: test-${{ matrix.target }}
          message: ${{ job.status }}
          message-color: ${{ job.status == 'success' && 'green' || 'red' }}
          file-name: badges/test-${{ matrix.target }}.svg
          badge-branch: badges
          github-token: "${{ secrets.GITHUB_TOKEN }}"

