name: unit_test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            glslang-tools \
            python3

      - name: Cache zig build
        uses: actions/cache@v4
        with:
          path: .zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'build.zig.zon') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'build.zig.zon') }}-
            ${{ runner.os }}-zig-

      - name: Build and Run tests
        run: zig build test
